### ISSUE TITLE
When adding UPM Git Extension 11 errors all related to 

### ISSUE THREAD

**Issue by francescoStrada** [mob-sakai/UpmGitExtension#128]
I get a series of 11 errors as soon as I add the package to the project, and compilation ends. And they seem all related to; 

"....and no accessible extension method 'packageInfo' accepting a first argument of type 'UpmPackageVersion' could be found...."

Unity Version: 2020.3.43f1
OS: Windows 10

One full error message is:

Library\PackageCache\com.coffee.upm-git-extension@2.0.1\Editor\Coffee.UpmGitExtension\Extensions\UpmPackageVersionEx.cs(33,92): error CS1061: 'UpmPackageVersion' does not contain a definition for 'packageInfo' and no accessible extension method 'packageInfo' accepting a first argument of type 'UpmPackageVersion' could be found (are you missing a using directive or an assembly reference?)

This file contains all 11 errors dumped by the Editor console.
[error-messages.txt](https://github.com/mob-sakai/UpmGitExtension/files/10492657/error-messages.txt)

**Comment by francescoStrada** [comment]
Not working with UPM extension v2.0.1 and v2.0.0

**Comment by gebirgsbaerbel** [comment]
I have exactly the same issue with Unity 2021.3.12f1.

**Comment by batasbre** [comment]
Same issue here on Unity 2021.3.16f1
