### ISSUE TITLE
develop branch doesn't compile on 2021 LTS (2021.3.1.f1)

### ISSUE THREAD

**Issue by SixParQuatre** [mob-sakai/UpmGitExtension#118]
**Describe the bug**
Compile error
Packages\UpmGitExtension\Editor\Coffee.UpmGitExtension\UpmGitExtension.cs(70,43): error CS0246: The type or namespace name 'PackageManagerToolbar' could not be found (are you missing a using directive or an assembly reference?)

Note: 
The preview branch - which, if I'm understanding correctly, is less up to date than develop but has the same version number- doesn't have the error.

**To Reproduce**
1. Have 2021.3.1f1 installed
2. Add the package to your project as a local cutom packag; synch develop branch to latest (which is supposed to work for 2021.1 and later)

**Expected behavior**
Code should compile

**Environment (please complete the following information):**
 - Version:  2.0.0-preview.1
 - Platform: Windows
 - Unity version: 2021.3.f1
 - Build options: [e.g. IL2CPP, .Net 4.x, LWRP]

**Comment by seghcder** [comment]
I'm running on Unity 2021.3.1f1 LTS on the 2.0.0-preview.1 tag ... It runs ok but it has this issue https://github.com/mob-sakai/UpmGitExtension/issues/116 - using Mono though.

**Comment by SixParQuatre** [comment]
> I'm running on Unity 2021.3.1f1 LTS on the 2.0.0-preview.1 tag ... It runs ok but it has this issue #116 - using Mono though.

Yes that's what I'm saying in the original ticket: 2.0.0 preview.1 (which is one commit behind master) works, but master doesn't.
