### ISSUE TITLE
Doesn't work with 2020.3.12f1

### ISSUE THREAD

**Issue by ThomasBousquet** [mob-sakai/UpmGitExtension#115]
After adding it to the package manager, the following errors appear in the console at **AvailableVersions.cs(12,6)  and (42,6)**
`error CS0433: The type 'SerializableAttribute' exists in both 'Antlr4.Runtime.Standard, Version=4.7.2.0, Culture=neutral, PublicKeyToken=e78b2c5abd1fcb3f' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`

As a note: the extension worked with 2020.3.11f1

**Comment by firdiar-agate** [comment]
> Sorry for my late reply. Please try to use `2.0.0-preview.1` 👍

how to install `2.0.0-preview.1` ? could you give a reference

**Comment by firdiar-agate** [comment]
i tried to change the hash with 2.0.0-preview.1 commit `7a00a38eb83c0f1e36d2c82abb507c2d7895bc82` and it works thankyouu, 
i but i think it not the propper way, could you tell me how to install it directly from link?

**Comment by yoiang** [comment]
@firdiar-agate 
if you are using the `manifest.json` you can specific all sorts of nifty things including the commit or tag:

```json
{
  "dependencies": {
    "com.coffee.upm-git-extension": "https://github.com/mob-sakai/UpmGitExtension.git#7a00a38",
    ...
  },
}
```

```json
{
  "dependencies": {
    "com.coffee.upm-git-extension": "https://github.com/mob-sakai/UpmGitExtension.git#2.0.0-preview.1",
    ...
  },
}
```
